### ISSUE TITLE
BUG(bad link): Home screen bad link for admin/coordinator

### ISSUE THREAD

**Issue by h07r0d** [dave0/leaguerunner#69]
templates/pages/home.tpl
line 31
-- | &lt;a href="{lr_url path="league/schedule/`$l->league_id`"}">schedule</a>
++ | &lt;a href="{lr_url path="schedule/view/`$l->league_id`"}">schedule</a>

my commits tend to be a bit messy, so I didn't want to submit a bastard patch file

**Comment by dave0** [comment]
Thanks!  Fix is pushed now, along with a pile of other stuff I hadn't gotten around to yet.
