### ISSUE TITLE
Add Address to ICAL listing LOCATION field.

### ISSUE THREAD

**Issue by mmasse** [dave0/leaguerunner#75]
Currently when using ICAL to add games to your calendar. 
The LOCATION: field does not contain the field address. 

Example of current ICAL event:

-------------snip---------------
BEGIN:VEVENT
UID:37806-ocua.ca
DTSTAMP:20121011T211517Z
CREATED:20121011T211517Z
LAST-MODIFIED:20121011T211517Z
DTSTART;TZID=US/Eastern:20121016T183000
DTEND;TZID=US/Eastern:20121016T203000

LOCATION:Laroche 2 (LAR 2)

X-LOCATION-URL:http://www.ocua.ca/leaguerunner/field/view/202
SUMMARY:Deep Space Lime (fall) (home) vs. The Mooseheads - Fall (away)
DESCRIPTION:Game 37806: Deep Space Lime (fall) (home) vs. The Mooseheads - Fall (away) at Laroche 2 (LAR 2) on Tue Oct 16 2012 18:30 to 20:30(they wear Lime Green/Green)
X-OPPONENT-COLOUR: Lime Green/Green
END:VEVENT
-------------snip---------------

My smart phone (and I am assuming most other peoples smart phones as well) will navigate me to the field if the address is entered as.

LOCATION: 42 Stonehurst Avenue Ottawa, Ontario (LAR 2)
or
LOCATION: 42 Stonehurst Avenue Ottawa, Ontario (Laroche 2)

Thanks
Matt

**Comment by mmasse** [comment]
I don't know how to add the Feature request tag

**Comment by mmasse** [comment]
And close does not close the window, but closes the ticket, lol

**Comment by dave0** [comment]
Should be fixed now, both in OCUA production and in the Github tree

**Comment by mmasse** [comment]
Yay, thanks Dave, works great
